name: gallery_zoom_slides
description: Image pan gesture, pinch zoomin-zoomout, double tap zoomin-zoomout
version: 0.1.2
homepage: https://github.com/Dharini17/gallery_zoom_slides
documentation: https://pub.dev/documentation/gallery_zoom_slides

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: 'Theme1 look'
    path: screenshots/screenshot1.png
  - description: 'Theme2 look'
    path: screenshots/screenshot2.png
  - description: 'Theme3 look'
    path: screenshots/screenshot3.png
  - description: 'Theme4 look'
    path: screenshots/screenshot4.png
  - description: 'Theme5 look'
    path: screenshots/screenshot5.png
  - description: 'Theme6 look'
    path: screenshots/screenshot6.png