name: gallery_zoom_slides
description: Image pan gesture, pinch zoomin-zoomout, double tap zoomin-zoomout
version: 0.0.7
homepage: https://github.com/Dharini17/gallery_zoom_slides
documentation: https://pub.dev/documentation/gallery_zoom_slides

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0